--36.
SELECT MASP, COUNT(DISTINCT MASP) AS 'TỔNG SÓ' FROM SANPHAM
WHERE MASP IN(SELECT MASP FROM CTHD INNER JOIN HOADON ON CTHD.SOHD = HOADON.SOHD
WHERE MONTH(NGHD) = 10 AND YEAR(NGHD) = 2006) GROUP BY MASP
--37
SELECT MONTH(NGHD) AS ' THÁNG',  SUM(TRIGIA) AS ' DOANH THU' FROM HOADON WHERE YEAR(NGHD) = 2006 GROUP BY MONTH(NGHD)
--38
SELECT * FROM HOADON where SOHD IN ( SELECT SOHD FROM CTHD WHERE SL>=4)
--39
SELECT * FROM HOADON WHERE SOHD IN ( SELECT SOHD FROM CTHD INNER JOIN SANPHAM ON CTHD.MASP = SANPHAM.MASP 
WHERE NUOCSX = UPPER('VIET NAM') AND  SL>=3)
--CAU 40
SELECT MAKH , HOTEN FROM KHACHHANG WHERE MAKH =(SELECT TOP 1 MAKH FROM HOADON GROUP BY MAKH ORDER BY COUNT(DISTINCT SOHD) DESC)
--cau 41
select top 1 month(NGHD) AS ' THÁNG CÓ DOANH SỐ CAO NHẤT ' FROM HOADON 
WHERE YEAR(NGHD)= 2006 GROUP BY MONTH(NGHD) ORDER BY SUM(TRIGIA) DESC
--CAU 42
SELECT MASP, TENSP FROM SANPHAM 
WHERE MASP =(SELECT TOP 1 MASP FROM CTHD GROUP BY MASP ORDER BY SUM(SL) DESC)
--CAU 43
SELECT M.NUOCSX,MASP,TENSP FROM (SELECT NUOCSX , MAX(GIA) AS 'H' FROM SANPHAM 
GROUP BY NUOCSX) AS M LEFT JOIN SANPHAM ON SANPHAM.GIA = M.H WHERE M.NUOCSX = SANPHAM.NUOCSX
--CAU 44
SELECT NUOCSX FROM SANPHAM GROUP BY NUOCSX HAVING COUNT(GIA)>=3
--cau 45
SELECT *FROM KHACHHANG
WHERE MAKH = (SELECT TOP 1 TOP10.MAKH FROM (SELECT TOP 10 MAKH FROM KHACHHANG
ORDER BY DOANHSO DESC) AS TOP10
LEFT JOIN 
(SELECT MAKH, COUNT(SOHD) AS SOLAN
FROM HOADON
GROUP BY MAKH) AS LUOTMUA
ON TOP10.MAKH = LUOTMUA.MAKH
ORDER BY SOLAN DESC)