--CAU1
CREATE DATABASE QLHANG

USE QLHANG
 GO
create table VATTU(
 MAVT NVARCHAR(4),
 TENVT NVARCHAR(40),
 DVTINH NVARCHAR(10),
 SLCON INT
 CONSTRAINT PK_VATTU PRIMARY KEY(MAVT)
)
CREATE TABLE HDBAN(
 MAHD NVARCHAR(4) ,
 NGAYXUAT SMALLDATETIME,
 HOTENKHACH NVARCHAR(50),
 CONSTRAINT PK_HDBAN PRIMARY KEY(MAHD)
 )
 CREATE TABLE HANGXUAT(
 MAHD NVARCHAR(4),
 MAVT NVARCHAR(4),
 DONGIA MONEY,
 SLBAN INT,
 CONSTRAINT PK_HANGXUAT PRIMARY KEY(MAHD,MAVT)
 )

 ALTER TABLE HANGXUAT ADD CONSTRAINT fK_01 FOREIGN KEY (MAHD) REFERENCES HDBAN(MAHD)
 ALTER TABLE HANGXUAT ADD CONSTRAINT fK_02 FOREIGN KEY (MAVT) REFERENCES VATTU(MAVT)

 --INSERT DU LIEU


 INSERT INTO VATTU values('0001','fanta','loc','80')
 INSERT INTO VATTU values('0002','pepsi','loc','300')

 insert into HDBAN values('0008','2022/5/16','Danny Nguyen')
  insert into HDBAN values('0010','2022/7/6','Dustin Nguyen')

  insert into HANGXUAT values('0010','0001','30000','50')
  insert into HANGXUAT values('0008','0002','35000','150')
  insert into HANGXUAT values('0010','0002','35000','50')
  insert into HANGXUAT values('0008','0001','30000','25')

  --Cau2

  SELECT TOP 1MAHD ,(DONGIA*SLBAN) AS TONGTIEN FROM HANGXUAT ORDER BY TONGTIEN DESC

  --cau3
CREATE FUNCTION C3 (
    @MAHD varchar(10)
)
RETURNS TABLE
AS
RETURN
    SELECT 
        HANGXUAT.MAHD,
        HDBAN.NGAYXUAT,
        HANGXUAT.MAVT,
        HANGXUAT.DONGIA,
        HANGXUAT.SLBAN,  
        CASE
            WHEN DATENAME(weekday,HDBAN.NGAYXUAT) = 'Monday' THEN N'Thứ hai'            
            WHEN DATENAME(weekday,HDBAN.NGAYXUAT) = 'Tuesday' THEN N'Thứ ba'
            WHEN DATENAME(weekday,HDBAN.NGAYXUAT) = 'Wednesday' THEN N'Thứ tư'
            WHEN DATENAME(weekday,HDBAN.NGAYXUAT) = 'Thursday' THEN N'Thứ năm'
            WHEN DATENAME(weekday,HDBAN.NGAYXUAT) = 'Friday' THEN N'Thứ sáu'
            WHEN DATENAME(weekday,HDBAN.NGAYXUAT) = 'Saturday' THEN N'Thứ bảy'
            ELSE N'Chủ nhật'	
        END AS NGAYTHU
    FROM HANGXUAT INNER JOIN HDBAN ON HANGXUAT.MAHD = HDBAN.MAHD
    WHERE HANGXUAT.MAHD = @MAHD;
		SELECT * FROM C3('0008')
  --CAU4
  CREATE PROCEDURE C4 
@THANG int, @NAM int 
AS
SELECT (SLBAN * DONGIA) AS TONGTIEN FROM HANGXUAT INNER JOIN HDBAN ON HANGXUAT.MAHD = HDBAN.MAHD
where MONTH(HDBAN.NGAYXUAT) = @THANG AND YEAR(HDBAN.NGAYXUAT) = @NAM;

SELECT * FROM C4('0008')